# stock_universe.py

# Nifty 50 Stocks
nifty_50 = [
    'ADANIENT.NS', 'ADANIPORTS.NS', 'ASIANPAINT.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS',
    'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BPCL.NS', 'BHARTIARTL.NS', 'BRITANNIA.NS',
    'CIPLA.NS', 'COALINDIA.NS', 'DIVISLAB.NS', 'DRREDDY.NS', 'EICHERMOT.NS',
    'GRASIM.NS', 'HCLTECH.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HEROMOTOCO.NS',
    'HINDALCO.NS', 'HINDUNILVR.NS', 'ICICIBANK.NS', 'ITC.NS', 'INDUSINDBK.NS',
    'INFY.NS', 'JSWSTEEL.NS', 'KOTAKBANK.NS', 'LT.NS', 'M&M.NS',
    'MARUTI.NS', 'NESTLEIND.NS', 'NTPC.NS', 'ONGC.NS', 'POWERGRID.NS',
    'RELIANCE.NS', 'SBILIFE.NS', 'SBIN.NS', 'SUNPHARMA.NS', 'TCS.NS',
    'TATACONSUM.NS', 'TATAMOTORS.NS', 'TATASTEEL.NS', 'TECHM.NS', 'TITAN.NS',
    'UPL.NS', 'ULTRACEMCO.NS', 'WIPRO.NS', 'LTIM.NS', 'HINDPETRO.NS'
]

# Nifty Midcap 100 Stocks
midcap_100 = [
    'ABB.NS', 'APLAPOLLO.NS', 'ASHOKLEY.NS', 'ASTRAL.NS', 'AUROPHARMA.NS',
    'BALKRISIND.NS', 'BANKINDIA.NS', 'BERGEPAINT.NS', 'BHEL.NS', 'CANBK.NS',
    'CUMMINSIND.NS', 'DALBHARAT.NS', 'DEEPAKNTR.NS', 'EIDPARRY.NS', 'ESCORTS.NS',
    'FEDERALBNK.NS', 'GMRINFRA.NS', 'GODREJCP.NS', 'GUJGASLTD.NS', 'HAL.NS',
    'HAVELLS.NS', 'HINDZINC.NS', 'IDFCFIRSTB.NS', 'INDHOTEL.NS', 'INDIGO.NS',
    'JINDALSTEL.NS', 'JUBLFOOD.NS', 'LALPATHLAB.NS', 'LINDEINDIA.NS', 'MAHABANK.NS',
    'MAHINDCIE.NS', 'MANAPPURAM.NS', 'MGL.NS', 'MPHASIS.NS', 'MRPL.NS',
    'NHPC.NS', 'NMDC.NS', 'OBEROIRLTY.NS', 'OFSS.NS', 'PAGEIND.NS',
    'PFC.NS', 'PIDILITIND.NS', 'PNB.NS', 'POLYCAB.NS', 'POWERINDIA.NS',
    'RAJESHEXPO.NS', 'RECLTD.NS', 'SAIL.NS', 'SANOFI.NS', 'SCHAEFFLER.NS',
    'SHREECEM.NS', 'SIEMENS.NS', 'SRF.NS', 'SUNTV.NS', 'SUPREMEIND.NS',
    'SYNGENE.NS', 'TATACHEM.NS', 'TATACOMM.NS', 'TRENT.NS', 'TVSMOTOR.NS',
    'UBL.NS', 'UNIONBANK.NS', 'VBL.NS', 'VOLTAS.NS', 'WHIRLPOOL.NS',
    'ZEEL.NS', 'ZYDUSLIFE.NS', 'FORTIS.NS', 'LTTS.NS', 'NAVINFLUOR.NS',
    'TORNTPHARM.NS', 'IGL.NS', 'BANKBARODA.NS', 'GSPL.NS', 'CHOLAFIN.NS',
    'COFORGE.NS', 'CREDITACC.NS', 'CROMPTON.NS', 'DIXON.NS', 'LICI.NS',
    'METROPOLIS.NS', 'NAM-INDIA.NS', 'INDIAMART.NS', 'SJVN.NS', 'IRFC.NS',
    'IDBI.NS', 'RVNL.NS', 'IRCON.NS', 'BEML.NS', 'TATAPOWER.NS',
    'CANFINHOME.NS', 'BSOFT.NS', 'BALRAMCHIN.NS', 'TV18BRDCST.NS', 'NH.NS'
]

# Combined Stock List
stock_list = nifty_50 + midcap_100
